#### Q10.Create a 2x2 matrix A and a 2x2 matrix B.Perform matrix multiplication using np.dot() or the @ operator.

In [1]:
import numpy as np

In [2]:
A = np.array([[1,2],
              [3,4]])

In [3]:
B= np.array([[5,6],
             [7,8]])

In [4]:
print("Matrix A:")
print(A)

Matrix A:
[[1 2]
 [3 4]]


In [5]:
print("Matrix B:")
print(B)

Matrix B:
[[5 6]
 [7 8]]


In [6]:
print("Matrix Multiplication:")
print(np.dot(A,B))

Matrix Multiplication:
[[19 22]
 [43 50]]
