#### Q12.Create a 3x3 array and a 1D array with 3 elements.Add the 1D array to the 2D array.Explain how broadcasting works in this operation.

In [1]:
import numpy as np

In [3]:
arr2d = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

In [4]:
arr1d = np.array([10,20,30])

In [5]:
result = arr2d+arr1d

In [6]:
print("2D Array:")
print(arr2d)

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
print("1D Array:")
print(arr1d)

1D Array:
[10 20 30]


In [8]:
print("Result:")
print(result)

Result:
[[11 22 33]
 [14 25 36]
 [17 28 39]]
