#### Q13.Create a 4x4 array of random integers.Find the maximum,minimum,and mean of the entire array.

In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,101,size = (4,4))

In [3]:
print("Array:")
print(arr)

Array:
[[44 41  2 30]
 [23 48 33 92]
 [30 50 46 51]
 [38 91 64 86]]


In [4]:
print("Maximum:",np.max(arr))

Maximum: 92


In [5]:
print("Minimum:",np.min(arr))

Minimum: 2


In [6]:
print("Mean:",np.mean(arr))

Mean: 48.0625
