#### Q14.Find the row-wise and column-wise sums.

In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

            

In [3]:
print("Array:")
print(arr)

Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
print("Row -wise sum:",np.sum(arr,axis=1))

Row -wise sum: [ 6 15 24]


In [6]:
print("Column-Wise sum:",np.sum(arr,axis=0))

Column-Wise sum: [12 15 18]
