#### Q.16.Generate a 5x5 matrix of random floats between 0 and 1.

In [1]:
import numpy as np

In [2]:
arr = np.random.rand(5,5)

In [3]:
print("Random Float Matrix:")
print(arr)

Random Float Matrix:
[[0.46749712 0.81574957 0.43888459 0.39768839 0.10032531]
 [0.77842391 0.34722329 0.94063146 0.36740404 0.31726552]
 [0.72093609 0.64955902 0.90839495 0.91908639 0.84984799]
 [0.79002353 0.99954271 0.79028551 0.81964404 0.92615417]
 [0.11886062 0.40094493 0.2083639  0.90274089 0.3960826 ]]
