#### Q4.Given a 2D array, find its shape and size.Create a 5x4 array with random integers between 1 and 100,
#### and print the shape and size

In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,101,size=(5,4))
print(arr)
print("Shape:",arr.shape)
print("Size:",arr.size)

[[ 53  71  78   1]
 [ 84  26  30  94]
 [ 23  41   5  35]
 [ 69  77  10   2]
 [100  32  56   5]]
Shape: (5, 4)
Size: 20
