#### Q5.Create a 3x3 array of integers and access:

##### a.The second element of the first row

In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
print("a.",arr[0,1])

a. 2


##### b.The third column of the 2nd row

In [5]:
print("b.",arr[1,2])

b. 6


##### c. A subarray with the first two rows and last two columns

In [6]:
print("c.")
print(arr[0:2,1:3])

c.
[[2 3]
 [5 6]]
