#### Q6.Create a 1D array of 12 elements. Reshape it into a 3x4 2D array.

In [1]:
import numpy as np

In [2]:
arr = np.arange(12)

In [3]:
new_arr = arr.reshape(3,4)

In [4]:
print("1D Array:")
print(arr)

1D Array:
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [5]:
print("3x4 Array:")
print(new_arr)

3x4 Array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
