#### Q8.Create two arrays of shape (2,3): arr1 and arr2. Perform element-wise addition,subtraction,multiplication,and division on them.

In [1]:
import numpy as np

In [2]:
arr1 =np.array([[10,20,30],
                [40,50,60]])

In [3]:
arr2 = np.array([[2,4,5],
                 [5,10,20]])

In [4]:
print("Addition:")
print(arr1+arr2)

Addition:
[[12 24 35]
 [45 60 80]]


In [5]:
print("Subtraction:")
print (arr1 - arr2)

Subtraction:
[[ 8 16 25]
 [35 40 40]]


In [6]:
print("Multiplication:")
print(arr1 * arr2)

Multiplication:
[[  20   80  150]
 [ 200  500 1200]]


In [7]:
print("Division:")
print(arr1/arr2)

Division:
[[5. 5. 6.]
 [8. 5. 3.]]
