#### Q3.Perform the following operations on an array of mobile phones prices 6999,7500,11999,27899,14999,9999

##### a.Create a 1d-array of mobile phones prices

In [1]:
import numpy as np

In [2]:
arr = np.array([6999,7500,11999,27899,14999,9999])
print("Original Array:")
print(arr)

Original Array:
[ 6999  7500 11999 27899 14999  9999]


##### b.Convert this array to float type

In [3]:
arr=arr.astype(float)
print("\nFloat Array:")
print(arr)


Float Array:
[ 6999.  7500. 11999. 27899. 14999.  9999.]


##### c.Append a new mobile having price of 13999 Rs. to this array.

In [4]:
arr = np.append(arr,13999)
print("\n After Appending 13999:")
print(arr)


 After Appending 13999:
[ 6999.  7500. 11999. 27899. 14999.  9999. 13999.]


##### d.Reverse this array of mobile phones prices

In [5]:
arr = arr[::-1]
print("\nReversed Array:")
print(arr)


Reversed Array:
[13999.  9999. 14999. 27899. 11999.  7500.  6999.]


##### e.Apply GST of 18% on mobile phones prices and update this array

In [6]:
arr = arr*1.18
print("\nAfter applying 18% GST:")
print(arr)


After applying 18% GST:
[16518.82 11798.82 17698.82 32920.82 14158.82  8850.    8258.82]


##### f.Sort the array in descending order of price

In [7]:
arr = np.sort(arr)[::-1]
print("\nSorted Array in Descending Order")
print(arr)


Sorted Array in Descending Order
[32920.82 17698.82 16518.82 14158.82 11798.82  8850.    8258.82]


##### g.What is the average mobile phone price

In [8]:
average = np.mean(arr)
print("\nAverage Mobile Phone Price:",average)


Average Mobile Phone Price: 15743.560000000001


##### h.What is the difference b/w maximum and minimum price

In [9]:
difference=np.max(arr)-np.min(arr)
print("Difference between Maximum and Minimum Price:",difference)

Difference between Maximum and Minimum Price: 24662.0
